config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#welcome'
  # Defines the root path route ("/")
  # root "articles#index"
  resources :shipping_companies, only: %i[index show new create edit update], shallow: true do
    resources :vehicles, only: %i[index show new create edit update destroy]
    resources :price_table, only: %i[index update]
    resources :price_line, only: %i[new create destroy]
    resources :delivery_time_table, only: [:index]
    resources :delivery_time_line, only: %i[new create destroy]
    resources :order, only: %i[index show new create update] do
      post 'new_ul', on: :member
    end
    resources :update_line, only: [:create]

    get 'budget_query', on: :collection
    get 'budget_response', on: :collection
    patch 'status_change', on: :member
    patch 'minimum_value_update', on: :member
  end
  get '/search', to: 'order#search'
end

app/models/shipping_company.rb
# frozen_string_literal: true

class ShippingCompany < ApplicationRecord
  validates :name, :corporate_name, :email_domain, :cnpj, :billing_adress, presence: true
  validates :cnpj, format: { with: %r{\A\d{2}\.\d{3}\.\d{3}/\d{4}-\d{2}\z} }
  validates :email_domain, format: { with: /\A([\w-]+\.)+[\w-]+\z/ }
  validates :cnpj, uniqueness: true
  has_many :users, dependent: :destroy
  has_one :price_table, dependent: :destroy
  has_one :delivery_time_table, dependent: :destroy
end

app/controllers/shipping_companies_controller.rb
# frozen_string_literal: true

class ShippingCompaniesController < ApplicationController
  before_action :authenticate_admin!, only: %i[new index budget_query budget_response]
  before_action :visit_blocker, only: %i[show minimum_value_update]

  def index
    @shipping_companies = ShippingCompany.all
  end

  def show
    id = params[:id]
    @shipping_company = ShippingCompany.find(id)
  end

  def new
    @shipping_company = ShippingCompany.new
  end

  def create
    sc_parameters = params.require(:shipping_company).permit(:name, :corporate_name, :cnpj,
                                                             :billing_adress, :active, :email_domain)
    @shipping_company = ShippingCompany.new(sc_parameters)

    if @shipping_company.save
      redirect_to @shipping_company, notice: t('.success')
    else
      errors = @shipping_company.errors.full_messages.join(', ')
      flash.now[:alert] = t('.failure') + errors
      render 'new'
    end
  end

  def edit
    id = params[:id]
    @shipping_company = ShippingCompany.find(id)
  end

  def update
    id = params[:id]
    parameters = params.require(:shipping_company).permit(:name, :corporate_name, :email_domain, :cnpj, :billing_adress)

    @shipping_company = ShippingCompany.find(id)

    if @shipping_company.update(parameters)
      redirect_to shipping_company_path(id), notice: t('.success')
    else
      errors = @shipping_company.errors.full_messages.join(',')
      flash[:alert] = t('.failure') + errors
      render 'edit'
    end
  end

  def status_change
    # could be set directly on update
    id = params[:id]
    param_status = params.permit(:active)

    @shipping_company = ShippingCompany.find(id)
    @shipping_company.update(param_status)

    redirect_to shipping_company_path(id), notice: t('.success')
  end

  def minimum_value_update
    id = params[:id]
    parameters = params.require(:shipping_company).permit(:minimum_value)
    @shipping_company = ShippingCompany.find(id)
    formated_value = parameters[:minimum_value].tr(',', '').to_i
    @shipping_company.update!('minimum_value' => formated_value.to_s)

    redirect_to shipping_company_price_table_index_path(@shipping_company)
  end

  def budget_query; end

  def budget_response
    parameters_raw = params.permit(:width, :height, :depth, :weight, :distance)
    @hashes = BudgetFinder.find_budgets(parameters_raw)

    redirect_to budget_query_shipping_companies_path, alert: t('.no_results') if @hashes.empty?
  end

  private

  def visit_blocker
    redirect_to new_user_session_path unless user_signed_in? || admin_signed_in?
  end
end

app/views/shipping_companies/_form.html.erb
<%= form_with model: @shipping_company do |form|%>
  <div>
    <%= form.label :name%>
    <%= form.text_field :name%>
  </div>
  <div>
    <%= form.label :corporate_name%>
    <%= form.text_field :corporate_name%>
  </div>
  <div>
    <%= form.label :cnpj%>
    <%= form.text_field :cnpj%>
  </div>
  <div>
    <%= form.label :billing_adress%>
    <%= form.text_field :billing_adress%>
  </div>
  <div>
    <%= form.label :email_domain%>
    <%= form.text_field :email_domain%>
  </div>
  <%= form.submit%>
<%end%>

app/views/shipping_companies/budget_query.html.erb
<%=form_with url: budget_response_shipping_companies_path, method: :get do |f|%>
  <%=f.label :width, 'Largura'%>
  <%=f.number_field :width%>
  <%=f.label :height, 'Altura'%>
  <%=f.number_field :height%>
  <%=f.label :depth, 'Profundidade'%>
  <%=f.number_field :depth%>
  <div>
    <%=f.label :weight, 'Peso'%>
    <%=f.number_field :weight%>
    <%=f.label :distance, 'Distância'%>
    <%=f.number_field :distance%>
  </div>
  <%=f.submit 'Consultar'%>
<%end%>

app/views/shipping_companies/budget_response.html.erb
<% @hashes.each do |h|%>
  <div>
    <%= link_to(h[:name], shipping_company_path(h[:id]))%> - R$<%=money_format(h[:value])%> - <%=h[:days]%> dias
  </div>
<% end%>

app/views/shipping_companies/edit.html.erb
<%= form_with model: @shipping_company, url: "/shipping_companies/#{@shipping_company.id}" do |form|%>
  <div>
    <%= form.label :name%>
    <%= form.text_field :name%>
  </div>
  <div>
    <%= form.label :corporate_name%>
    <%= form.text_field :corporate_name%>
  </div>
  <div>
    <%= form.label :cnpj%>
    <%= form.text_field :cnpj%>
  </div>
  <div>
    <%= form.label :billing_adress%>
    <%= form.text_field :billing_adress%>
  </div>
  <div>
    <%= form.label :email_domain%>
    <%= form.text_field :email_domain%>
  </div>
  <%= form.submit%>
<%end%>

app/views/shipping_companies/new_order.html.erb
<%= form_with model: @order, url: create_order_path(@id) do |form|%>
  <div>
    <%= form.label :pickup_adress, 'Endereço para retirada'%>
    <%= form.text_field :pickup_adress%>
  </div>
  <div>
    <%= form.label :product_code, 'Código do produto'%>
    <%= form.text_field :product_code%>
  </div>
  <div>
    <%= form.label :width, 'Largura'%>
    <%= form.number_field :width%>
    <%= form.label :height, 'Altura'%>
    <%= form.number_field :height%>
    <%= form.label :depth, 'Profundidade'%>
    <%= form.number_field :depth%>
    <%= form.label :weight, 'Peso'%>
    <%= form.number_field :weight%>
  </div>
  <div>
    <%= form.label :delivery_adress, 'Endereço para entrega'%>
    <%= form.text_field :delivery_adress%>
  </div>
  <div>
    <%= form.label :cpf, 'CPF do destinatário'%>
    <%= form.text_field :cpf%>
  </div>
  <div>
    <%= form.label :distance, 'Distância total'%>
    <%= form.text_field :distance%>
  </div>
  <%= form.submit 'Cadastrar'%>
<%end%>

app/views/shipping_companies/show.html.erb
<div>
  <%= @shipping_company.name%>
</div>
<div>
Razão social: <%= @shipping_company.corporate_name%>
</div>
<div>
CNPJ: <%= @shipping_company.cnpj%>
</div>
<div>
Endereço para faturamento: <%= @shipping_company.billing_adress%>
</div>
<div>
  <% if @shipping_company.active == true%>
    Está ativa
  <% else%>
    Está inativa
  <%end%>
</div>
<div>
Domínio de e-mail: <%= @shipping_company.email_domain%>
</div>


<%if admin_signed_in?%>
  <div>
    <%= link_to 'Ordens de Serviço', shipping_company_order_index_path(@shipping_company.id)%>
  </div>
  <div>
    <%= link_to 'Editar', edit_shipping_company_path%>
  </div>
  <%if @shipping_company.active == true%>
    <div>
      <%= button_to 'Desativar', status_change_shipping_company_path(@shipping_company.id), method: :patch, params: {:active => false}%>
    </div>
  <%else%>
    <div>
      <%= button_to 'Reativar', "/shipping_companies/#{@shipping_company.id}", method: :patch, params: {:active => true}%>
    </div>
  <%end%>
<%end%>

app/views/shipping_companies/show_order.html.erb
<h3><%=@order.code%></h3>
<dl>
  <dt>Transportadora - </dt>
    <dd><%=@order.shipping_company.name%></dd>
  <dt>Distância Km - </dt>
    <dd><%=@order.distance%></dd>
  <dt>Orçamento - </dt>
    <dd>R$<%=money_format(@order.value)%></dd>
  <dt>Data de entrega - </dt>
    <dd><%=@order.date%></dd>
  <dt>Código do produto - </dt>
    <dd><%=@order.product_code%></dd>
  <dt>Volume m³ - </dt>
    <dd><%=@order.width*@order.height*@order.depth%></dd>
  <dt>Peso Kg - </dt>
    <dd><%=@order.weight%></dd>
  <dt>Endereço de retirada - </dt>
    <dd><%=@order.pickup_adress%></dd>
  <dt>Endereço de entrega - </dt>
    <dd><%=@order.delivery_adress%></dd>
  <dt>CPF do destinatário - </dt>
    <dd><%=@order.cpf%></dd>
  <dt>Admin responsável - </dt>
    <dd><%=@order.admin.email%></dd>
  <dt>Status - </dt>
    <dd><%=@order.status%></dd>
  <%if @order.vehicle_id != nil%>
    <dt>Veículo - </dt>
      <dd><%=Vehicle.find(@order.vehicle_id).plate%></dd>
  <%end%>
</dl>

<% if user_signed_in? && @order.status == 'pendente' %>
  <%=form_with model: @order, url: update_order_path do |form|%>
    <%=form.label :vehicle_id, 'Veículo'%>
    <%=form.collection_select :vehicle_id, Vehicle.all, :id, :plate%>
    <%=form.hidden_field :status, value: :ativa%>
    <%=form.submit 'Aceitar'%>
  <%end%>
  <%=form_with model: @order, url: update_order_path do |form|%>
    <%=form.hidden_field :status, value: :cancelada%>
    <%=form.submit 'Negar'%>
  <%end%>
<%end%>