config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#welcome'
  # Defines the root path route ("/")
  # root "articles#index"
  resources :shipping_companies, only: %i[index show new create edit update], shallow: true do
    resources :vehicles, only: %i[index show new create edit update destroy]
    resources :price_table, only: %i[index update]
    resources :price_line, only: %i[new create destroy]
    resources :delivery_time_table, only: [:index]
    resources :delivery_time_line, only: %i[new create destroy]
    resources :order, only: %i[index show new create update] do
      post 'new_ul', on: :member
    end
    resources :update_line, only: [:create]

    get 'budget_query', on: :collection
    get 'budget_response', on: :collection
    patch 'status_change', on: :member
    patch 'minimum_value_update', on: :member
  end
  get '/search', to: 'order#search'
end

app/controllers/price_table_controller.rb
# frozen_string_literal: true

class PriceTableController < ApplicationController
  before_action :visit_blocker

  def index
    shipping_company_id = params[:shipping_company_id]
    @shipping_company = ShippingCompany.find(shipping_company_id)
    @price_line = PriceLine.where(shipping_company: shipping_company_id)
  end

  private

  def visit_blocker
    redirect_to new_user_session_path unless user_signed_in? || admin_signed_in?
  end
end

app/views/price_table/index.html.erb
<table>
  <tr>
    <th>Volume m³ |</th>
    <th>Peso Kg |</th>
    <th>Preço por Km</th>
  </tr>
  <% @price_line.each do |pl|%>
    <tr>
      <td><%= pl.minimum_volume%> - <%= pl.maximum_volume%></td>
      <td><%= pl.minimum_weight%> - <%= pl.maximum_weight%></td>
      <td>R$<%= money_format(pl.value)%></td>
      <td> <%=button_to 'Excluir', price_line_path(pl.id), method: :delete%></td>
    </tr>
  <%end%>
</table> 

<strong>Valor mínimo = R$<%=money_format(@shipping_company.minimum_value)%> </strong>
<div>
  <%= form_with model: @shipping_company, url: "/shipping_companies/#{@shipping_company.id}/minimum_value_update", method: :patch do |f|%>
    <%= f.label :minimum_value, 'Novo preço mínimo'%>
    <%= f.number_field :minimum_value, autocomplete: 'XX,XX'%>
    <%= f.submit 'Atualizar'%>
  <%end%>

</div>

<%=link_to 'Cadastrar Linha', new_shipping_company_price_line_path(@shipping_company)%>