config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#welcome'
  # Defines the root path route ("/")
  # root "articles#index"
  resources :shipping_companies, only: %i[index show new create edit update], shallow: true do
    resources :vehicles, only: %i[index show new create edit update destroy]
    resources :price_table, only: %i[index update]
    resources :price_line, only: %i[new create destroy]
    resources :delivery_time_table, only: [:index]
    resources :delivery_time_line, only: %i[new create destroy]
    resources :order, only: %i[index show new create update] do
      post 'new_ul', on: :member
    end
    resources :update_line, only: [:create]

    get 'budget_query', on: :collection
    get 'budget_response', on: :collection
    patch 'status_change', on: :member
    patch 'minimum_value_update', on: :member
  end
  get '/search', to: 'order#search'
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :admin
  belongs_to :shipping_company
  has_many :update_lines, dependent: :destroy

  enum status: { pendente: 0, ativa: 1, finalizada: 2, cancelada: 3 }
  before_validation :set_date, :set_value
  validate :shipping_company_cant_be_inactive, :vehicle_present_when_active, :vehicle_cannot_be_on_another_active_os
  validates :date, :value, :pickup_adress, :delivery_adress, :product_code, :width, :height, :depth, :cpf,
            presence: true
  validates :cpf, format: { with: /\A\d{3}\.\d{3}\.\d{3}-\d{2}\z/ }
  before_create :set_code

  private

  # Lacking admin confirmation validation

  def set_date
    delivery_times_array = DeliveryTimeLine.where(shipping_company: shipping_company)
    unless distance.nil? || delivery_times_array.empty?

      delivery_times_array.each do |dtl|
        initial_distance = dtl.init_distance
        final_distance = dtl.final_distance
        days = dtl.delivery_time
        self.date = Time.zone.today + days if distance < final_distance && distance > initial_distance
      end
    end
  end

  def set_value
    price_line_array = PriceLine.where(shipping_company: shipping_company)

    unless distance.nil? || price_line_array.empty? || width.nil? || height.nil? || depth.nil?
      volume = width * height * depth

      price_line_array.each do |pl|
        miv = pl.minimum_volume
        mav = pl.maximum_volume
        miw = pl.minimum_weight
        maw = pl.maximum_weight
        if miv < volume && mav > volume && miw < weight && maw > weight
          # Weight validation doesn't seem to be working
          self.value = pl.value * distance
        elsif volume < miv || weight < miw
          self.value = shipping_company.minimum_value * distance
        end
      end
    end
  end

  def set_code
    self.code = SecureRandom.alphanumeric(15).upcase
  end

  def shipping_company_cant_be_inactive
    errors.add(:shipping_company, ' não está ativa.') unless shipping_company.active?
  end

  def vehicle_present_when_active
    errors.add(:status, 'ativo requer veículo.') if status == 'ativa' && vehicle_id.nil?
  end

  def vehicle_cannot_be_on_another_active_os
    active_orders = Order.select(:vehicle_id).where(status: 1)

    if active_orders.any? && status == 'ativa' && !vehicle_id.nil?

      vehicles = Vehicle.select(:id).where(shipping_company_id: shipping_company_id, id: active_orders)
      vehicles_ids = vehicles.map(&:id)
      errors.add(:vehicle_id, 'já está em outra OS ativa.') if vehicles_ids.include?(vehicle_id)
    end
  end
end

app/controllers/order_controller.rb
# frozen_string_literal: true

class OrderController < ApplicationController
  before_action :authenticate_admin!, only: %i[new create]
  before_action :visit_blocker, except: %i[search show]

  def index
    id = params[:shipping_company_id]
    @shipping_company = ShippingCompany.find(id)
    @orders = Order.where(shipping_company: @shipping_company)
  end

  def show
    id = params[:id]
    @order = Order.find(id)
    @update_lines = UpdateLine.where(order: @order)
    @update_line_new = UpdateLine.new
    @ids = Order.select(:vehicle_id).where(status: 1)
    @vehicles = Vehicle.where(shipping_company_id: @order.shipping_company_id).where.not(id: @ids)
  end

  def new
    @id = params[:shipping_company_id]
    @order = Order.new
  end

  def create
    id = params[:shipping_company_id]
    order_parameters = params.require(:order).permit(:pickup_adress, :product_code, :width,
                                                     :height, :depth, :delivery_adress,
                                                     :cpf, :weight, :delivery_adress, :distance)
    @order = Order.new(order_parameters)
    @order.admin = current_admin
    @order.shipping_company = ShippingCompany.find(id)

    if @order.save
      redirect_to order_path(@order.id), notice: t('.success')
    else
      errors = @order.errors.full_messages.join(', ')
      flash.now[:alert] = t('.failure') + errors
      render 'new'
    end
  end

  def new_ul
    raw_line_params = params.permit(:latitude, :longitude, :order)
    str_line_params = "#{raw_line_params[:latitude]}, #{raw_line_params[:longitude]}"

    update_line = UpdateLine.new(coordinates: str_line_params, order_id: raw_line_params[:order])

    if update_line.save
      redirect_to order_path(update_line.order.id), notice: t('.success')
    else
      errors = update_line.errors.full_messages.join(', ')
      redirect_to order_path(update_line.order.id), notice: t('.failure') + errors
    end
  end

  def update
    id = params[:id]
    order_parameters = params.require(:order).permit(:vehicle_id, :status)
    @order = Order.find(id)
    @order.update!(order_parameters)

    redirect_to order_path(id)
  end

  def search
    code = params[:query]
    @order = Order.find_by(code: code)
    @update_lines = UpdateLine.where(order: @order)
    if @order.is_a?(Order)
      render :show
    else
      flash[:alert] = t('.no_results')
      redirect_to root_path
    end
  end

  private

  def visit_blocker
    redirect_to new_user_session_path unless user_signed_in? || admin_signed_in?
  end
end

app/views/order/index.html.erb
<% @orders.each do |os|%>
  <div>
    <%= link_to os.code, order_path(os.id)%> - <%= os.status%>
  </div>
<%end%>

<%if admin_signed_in?%>
  <%= link_to 'Cadastrar OS', new_shipping_company_order_path(@shipping_company.id)%>
<%end%>

app/views/order/new.html.erb
<%= form_with model: @order, url: "/shipping_companies/#{@id}/order" do |form|%>
  <div>
    <%= form.label :pickup_adress, 'Endereço para retirada'%>
    <%= form.text_field :pickup_adress%>
  </div>
  <div>
    <%= form.label :product_code, 'Código do produto'%>
    <%= form.text_field :product_code%>
  </div>
  <div>
    <%= form.label :width, 'Largura'%>
    <%= form.number_field :width%>
    <%= form.label :height, 'Altura'%>
    <%= form.number_field :height%>
    <%= form.label :depth, 'Profundidade'%>
    <%= form.number_field :depth%>
    <%= form.label :weight, 'Peso'%>
    <%= form.number_field :weight%>
  </div>
  <div>
    <%= form.label :delivery_adress, 'Endereço para entrega'%>
    <%= form.text_field :delivery_adress%>
  </div>
  <div>
    <%= form.label :cpf, 'CPF do destinatário'%>
    <%= form.text_field :cpf%>
  </div>
  <div>
    <%= form.label :distance, 'Distância total'%>
    <%= form.text_field :distance%>
  </div>
  <%= form.submit 'Cadastrar'%>
<%end%>

app/views/order/show.html.erb
<h3><%=@order.code%></h3>
<dl>
  <dt>Transportadora - </dt>
    <dd><%=@order.shipping_company.name%></dd>
  <dt>Distância Km - </dt>
    <dd><%=@order.distance%></dd>
  <dt>Orçamento - </dt>
    <dd>R$<%=money_format(@order.value)%></dd>
  <dt>Data de entrega - </dt>
    <dd><%=@order.date%></dd>
  <dt>Código do produto - </dt>
    <dd><%=@order.product_code%></dd>
  <dt>Volume m³ - </dt>
    <dd><%=@order.width*@order.height*@order.depth%></dd>
  <dt>Peso Kg - </dt>
    <dd><%=@order.weight%></dd>
  <dt>Endereço de retirada - </dt>
    <dd><%=@order.pickup_adress%></dd>
  <dt>Endereço de entrega - </dt>
    <dd><%=@order.delivery_adress%></dd>
  <dt>CPF do destinatário - </dt>
    <dd><%=@order.cpf%></dd>
  <dt>Admin responsável - </dt>
    <dd><%=@order.admin.email%></dd>
  <dt>Status - </dt>
    <dd><%=@order.status%></dd>
  <%if @order.vehicle_id != nil%>
    <dt>Veículo - </dt>
      <dd><%=Vehicle.find(@order.vehicle_id).plate%></dd>
  <%end%>
</dl>

<p>Histórico</p>
<% @update_lines.each do |ul|%>
  <div>
    <%= l ul.created_at%> -------------- <%= ul.coordinates%>
  </div> 
<%end%>

<% if user_signed_in? && @order.status == 'pendente' %>
  <%=form_with model: @order, url: "/order/#{@order.id}" do |form|%>
    <%=form.label :vehicle_id, 'Veículo'%>
    <%=form.collection_select :vehicle_id, @vehicles, :id, :plate%>
    <%=form.hidden_field :status, value: :ativa%>
    <%=form.submit 'Aceitar'%>
  <%end%>
  <%=form_with model: @order, url: "/order/#{@order.id}" do |form|%>
    <%=form.hidden_field :status, value: :cancelada%>
    <%=form.submit 'Negar'%>
  <%end%>
<% elsif user_signed_in? && @order.status == 'ativa' %>
  <%=form_with url: new_ul_order_path(@order.id) do |form|%>
    <%=form.label :latitude%>
    <%=form.number_field :latitude%>
    <%=form.label :longitude%>
    <%=form.number_field :longitude%>
    <%=form.hidden_field :order, value: @order.id%>
    <%=form.submit 'Atualizar'%>
  <%end%>
  <%=form_with model: @order, url: "/order/#{@order.id}" do |form|%>
    <%=form.hidden_field :status, value: :finalizada%>
    <%=form.submit 'Finalizar'%>
  <%end%>
  <%=form_with model: @order, url: "/order/#{@order.id}" do |form|%>
    <%=form.hidden_field :status, value: :cancelada%>
    <%=form.submit 'Cancelar'%>
  <%end%>
<%end%>