config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#welcome'
  # Defines the root path route ("/")
  # root "articles#index"
  resources :shipping_companies, only: %i[index show new create edit update], shallow: true do
    resources :vehicles, only: %i[index show new create edit update destroy]
    resources :price_table, only: %i[index update]
    resources :price_line, only: %i[new create destroy]
    resources :delivery_time_table, only: [:index]
    resources :delivery_time_line, only: %i[new create destroy]
    resources :order, only: %i[index show new create update] do
      post 'new_ul', on: :member
    end
    resources :update_line, only: [:create]

    get 'budget_query', on: :collection
    get 'budget_response', on: :collection
    patch 'status_change', on: :member
    patch 'minimum_value_update', on: :member
  end
  get '/search', to: 'order#search'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerceDeliverySystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h1><%= link_to 'Sistema de frete', root_path%></h1>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <% if admin_signed_in?%>
        <nav>
          <%=link_to("Consulta de Preço", budget_query_shipping_companies_path)%> | 
          <%=link_to("Transportadoras Cadastradas", shipping_companies_path)%> |
          <%=link_to("Cadastrar Transportadora", new_shipping_company_path)%> | 
          <%=button_to "Sair", destroy_admin_session_path, method: :delete%>
        </nav>
      <% elsif user_signed_in?%>
        <nav>
          <%=link_to("Minha Transportadora", shipping_company_path(current_user.shipping_company.id))%> | 
          <%=link_to("Ordens de Serviço", shipping_company_order_index_path(current_user.shipping_company.id))%> |
          <%=link_to("Veículos", shipping_company_vehicles_path(current_user.shipping_company.id))%> | 
          <%=link_to("Tabela de Preços", shipping_company_price_table_index_path(current_user.shipping_company))%> | 
          <%=link_to("Tabela de Prazos", shipping_company_delivery_time_table_index_path(current_user.shipping_company))%> |
          <%=button_to "Sair", destroy_user_session_path, method: :delete%>
        </nav>
      <%end%>
    </header>
    <%= yield %>
  </body>
</html>